socket-server:
  port: 8086
server:
  port: 3000
  tomcat:
    threads:
      max: 200
      min-spare: 10
    max-connections: 400
    accept-count: 100
spring:
  master:
    datasource:
      jdbcUrl: jdbc:mysql://localhost:3307/ecommerce
      username: root
      password: 123456
      driverClassName: com.mysql.cj.jdbc.Driver
  slave:
    datasource:
      jdbcUrl: jdbc:mysql://localhost:3308/ecommerce
      username: root
      password: 123456
      driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
  data:
    redis:
      host: localhost
      port: 6379

  cache:
    type: redis
  sql:
    init:
      mode: never
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 77525743447-o1civ812em7pqos90ss5a52a60sv1edc.apps.googleusercontent.com
            client-secret: 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
            scope: email, profile
jwt:
  access-token-secret: uei7iTI9yFKPeu5wL2pAne0KX2J_sJPq7c4-lRIwF5E
  access-token-expiration-time: 3600000
  refresh-token-secret: uei7iTI9yFKPeu5wL2pAne0KX2J_sJPq7c4-lRIwF5E
  refresh-token-expiration-time: 86400000
cloudinary:
  cloud-name: dhwxpgxzl
  api-key: 683161372337227
  secret-key: eKL1dtmtWHG6NwYiw52-Ubnt4-U
  image-width: 500
  image-height: 500
  crop: fit
app:
  security:
    endpoints:
      public-urls:
        - /auth/login
        - /auth/register/*
        - /categories/**
        - /products
        - /products/*/details
        - /search
        - /seller/{id}/info
        - /seller/{id}/products
        - /chat/**
        - /app/message
        - /app/topic/messages
        - /payment
        - /address/**
        - /seller/public/**
        - /admin/**
        - /seller/**
      public-urls-regex:
        - /auth/login
        - /address/.*
        - /auth/register/.*
        - /categories/default
        - /categories/.*/children
        - /categories
        - /products
        - /products/.*/details
        - /seller/public/.*
    cors:
      allowed-origins:
        - http://localhost:5173
      allowed-headers:
        - Authorization
        - Content-Type
      allowed-methods:
        - GET
        - POST
        - PUT
        - DELETE
      credentials: true
  cookie:
    access-token:
      expiration-time: 7200
      same-site: none
      secure: true
      http-only: true
      path: /
  admin:
    email: admin@gmail.com
    password: admin123
    username: admin123
  snapshot:
    delay: 30000
    file-path: ./data/snapshot.dat
vn-pay:
  tmn-code: QGXVIH4M
  hash-secret: F31BKXHO8RNJ8M0ZLEEGANWVIVHXKJ2O
  url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  return-url: /payment
ghn:
  token: f29f99c6-3d9a-11f1-a973-aee5264794df
  calculate-ship-fee-url: https://dev-online-gateway.ghn.vn/shiip/public-api/v2/shipping-order/fee
  create-shop-url: https://dev-online-gateway.ghn.vn/shiip/public-api/v2/shop/register
  create-order-ship-url: https://dev-online-gateway.ghn.vn/shiip/public-api/v2/shipping-order/create
  get-order-ship-url: https://dev-online-gateway.ghn.vn/shiip/public-api/v2/shipping-order/detail-by-client-code
  create-shipment: https://dev-online-gateway.ghn.vn/shiip/public-api/v2/shipping-order/create