-- =========================================================
-- UPDATE ENUM permissions.val
-- =========================================================

ALTER TABLE permissions
MODIFY COLUMN val ENUM(
    'GET_INFO_CLIENT',
    'GET_ORDERS_NOTIFICATIONS_CLIENT',
    'GET_MESSAGES_NOTIFICATIONS_CLIENT',

    'GET_CART_SHOPPING',
    'ADD_CART_SHOPPING',
    'DELETE_CART_ITEMS',
    'GET_CART_SHOPPING_DELETED',
    'RESTORE_CART_SHOPPING_DELETED',

    'CREATE_ORDER',
    'GET_SHIPPING_INFO',
    'GET_CLIENT_ORDERS',
    'PAY_ORDER',
    'REQUEST_RETURN_ORDER',
    'REVIEW_RECEIVED_ORDER',
    'CANCEL_ORDER_BY_CLIENT',

    'CREATE_PRODUCT',
    'UPDATE_INFO_PRODUCT',
    'DELETE_PRODUCT',
    'GET_MY_PRODUCT',
    'VIEW_MY_PRODUCTS',
    'REVIEW_PRODUCT',

    'GET_STATUS_ORDER',
    'ACCEPT_ORDER',
    'CANCEL_ORDER_BY_SELLER',
    'APPROVE_RETURN_REQUEST',
    'VIEW_CLIENT_ORDERS',
    'VIEW_SELLER_ORDERS',

    'GET_SHOP_OVERVIEW',

    'GET_SHIPPER_INFO',
    'GET_SHIPPER_OVERVIEW',
    'GET_SUGGESTED_ORDER',
    'CHECKOUT_SUGGESTED_ORDER',
    'APPROVE_SUGGESTED_ORDER',
    'GET_RECEIVED_ORDER',
    'UPDATE_RECEIVED_ORDER',
    'GET_SHIPPER_REVENUE',
    'UPDATE_ORDER_TRACKING_LOCATION',
    'SHIP_ORDER',

    'GET_USERS_MANAGEMENT',
    'GET_USER_DETAILS_MANAGEMENT',
    'LOCK_USER',
    'UNLOCK_USER',

    'GET_PRODUCTS_MANAGEMENT',
    'BAN_PRODUCT',
    'UNBAN_PRODUCT',
    'APPROVE_PRODUCTS',
    'REJECT_PRODUCTS',
    'BAN_PRODUCTS',
    'UNLOCK_PRODUCTS',

    'GET_CATEGORIES_MANAGEMENT',
    'ADD_CATEGORY',


    'GET_TRANSACTIONS',
    'GET_TRANSACTION_DETAILS'
) NOT NULL;