package com.e_cormerce.shoppe.enums.user;

public enum ActionType {
  LOGIN,
  LOGOUT,
  ADD_TO_CART,
  CANCEL_ORDER,
  CREATE_PRODUCT,
  UPDATE_PRODUCT,
  DELETE_PRODUCT,
  HIDDEN_PRODUCT,
  UNHIDDEN_PRODUCT,
  CREATE_ORDER,
  UPDATE_ORDER,
  DELETE_ORDER,
  CLIENT_REGISTER,
  SELLER_REGISTER,
  ORDER_CREATED,
  ORDER_APPROVED,
  ORDER_PAID,
  ORDER_SHIPPING,
  ORDER_REQUIRE_REFUND,
  ORDER_CANCELLED_BY_CLIENT,
  ORDER_CANCELLED_BY_SELLER
}
