package com.e_cormerce.shoppe.enums;

public enum OrderStatus {
  PENDING,
  ACCEPTED,
  CANCELLED_BY_CLIENT,
  CANCELLED_BY_SHIPPER,
  CANCELLED_BY_SELLER,
  SHIPPING,
  ARRIVED,
  PAID,
  RETURN_REQUEST_BY_CLIENT,
  RETURN_REQUEST_BY_SHIPPER,
  RETURNED,
  BOMB
}
