package com.e_cormerce.shoppe.enums;

import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.experimental.FieldDefaults;

@Getter
@FieldDefaults(level = AccessLevel.PRIVATE)
@AllArgsConstructor
public enum PermissionEnum {
  REFRESH_TOKEN("REFRESH_TOKEN"),
  LOGOUT("LOGOUT"),
  VERIFY_USER("VERIFY_USER"),
  GET_PROFILE("GET_PROFILE"),
  EDIT_PROFILE("EDIT_PROFILE"),
  CHANGE_PASSWORD("CHANGE_PASSWORD"),
  GET_INFO_CLIENT("GET_INFO_CLIENT"),
  GET_ORDERS_NOTIFICATIONS_CLIENT("GET_ORDERS_NOTIFICATIONS_CLIENT"),
  GET_MESSAGES_NOTIFICATIONS_CLIENT("GET_MESSAGES_NOTIFICATIONS_CLIENT"),
  GET_CART_SHOPPING("GET_CART_SHOPPING"),
  ADD_CART_SHOPPING("ADD_CART_SHOPPING"),
  DELETE_CART_ITEMS("DELETE_CART_ITEMS"),
  GET_CART_SHOPPING_DELETED("GET_CART_SHOPPING_DELETED"),
  RESTORE_CART_SHOPPING_DELETED("RESTORE_CART_SHOPPING_DELETED"),
  CREATE_ORDER("CREATE_ORDER"),
  GET_SHIPPING_INFO("GET_SHIPPING_INFO"),
  GET_CLIENT_ORDERS("GET_CLIENT_ORDERS"),
  PAY_ORDER("PAY_ORDER"),
  REQUEST_RETURN_ORDER("REQUEST_RETURN_ORDER"),
  REVIEW_RECEIVED_ORDER("REVIEW_RECEIVED_ORDER"),
  CREATE_PRODUCT("CREATE_PRODUCT"),
  UPDATE_INFO_PRODUCT("UPDATE_INFO_PRODUCT"),
  DELETE_PRODUCT("DELETE_PRODUCT"),
  GET_MY_PRODUCT("GET_MY_PRODUCT"),
  GET_STATUS_ORDER("GET_STATUS_ORDER"),
  ACCEPT_ORDER("ACCEPT_ORDER"),
  APPROVE_RETURN_REQUEST("APPROVE_RETURN_REQUEST"),
  GET_SHOP_OVERVIEW("GET_SHOP_OVERVIEW"),
  GET_SHIPPER_INFO("GET_SHIPPER_INFO"),
  GET_SHIPPER_OVERVIEW("GET_SHIPPER_OVERVIEW"),
  GET_SUGGESTED_ORDER("GET_SUGGESTED_ORDER"),
  CHECKOUT_SUGGESTED_ORDER("CHECKOUT_SUGGESTED_ORDER"),
  APPROVE_SUGGESTED_ORDER("APPROVE_SUGGESTED_ORDER"),
  GET_RECEIVED_ORDER("GET_RECEIVED_ORDER"),
  UPDATE_RECEIVED_ORDER("UPDATE_RECEIVED_ORDER"),
  GET_SHIPPER_REVENUE("GET_SHIPPER_REVENUE"),
  GET_USERS_MANAGEMENT("GET_USERS_MANAGEMENT"),
  GET_USER_DETAILS_MANAGEMENT("GET_USER_DETAILS_MANAGEMENT"),
  LOCK_USER("LOCK_USER"),
  UNLOCK_USER("UNLOCK_USER"),
  GET_PRODUCTS_MANAGEMENT("GET_PRODUCTS_MANAGEMENT"),
  BAN_PRODUCT("BAN_PRODUCT"),
  UNBAN_PRODUCT("UNBAN_PRODUCT"),
  APPROVE_PRODUCTS("APPROVE_PRODUCTS"),
  APPROVE_PRODUCT("APPROVE_PRODUCT"),
  GET_CATEGORIES_MANAGEMENT("GET_CATEGORIES_MANAGEMENT"),
  ADD_CATEGORY("ADD_CATEGORY"),
  GET_TRANSACTIONS("GET_TRANSACTIONS"),
  GET_TRANSACTION_DETAILS("GET_TRANSACTION_DETAILS"),
  ;
  String val;
}
